export const stations = [
  { code: 'NDLS', name: 'New Delhi' },
  { code: 'CSMT', name: 'Chhatrapati Shivaji Maharaj Terminus' },
  { code: 'BCT', name: 'Mumbai Central' },
  { code: 'LTT', name: 'Lokmanya Tilak Terminus' },
  { code: 'HWH', name: 'Howrah Junction' },
  { code: 'MAS', name: 'Chennai Central' },
  { code: 'SBC', name: 'KSR Bengaluru City' },
  { code: 'YPR', name: 'Yesvantpur Junction' },
  { code: 'PUNE', name: 'Pune Junction' },
  { code: 'ADI', name: 'Ahmedabad Junction' },
  { code: 'ST', name: 'Surat' },
  { code: 'BRC', name: 'Vadodara Junction' },
  { code: 'CNB', name: 'Kanpur Central' },
  { code: 'LKO', name: 'Lucknow Charbagh NR' },
  { code: 'PRYJ', name: 'Prayagraj Junction' },
  { code: 'BSB', name: 'Varanasi Junction' },
  { code: 'DDU', name: 'Pt. DD Upadhyaya Junction' },
  { code: 'PNBE', name: 'Patna Junction' },
  { code: 'GHY', name: 'Guwahati' },
  { code: 'BBS', name: 'Bhubaneswar' },
  { code: 'VSKP', name: 'Visakhapatnam' },
  { code: 'BZA', name: 'Vijayawada Junction' },
  { code: 'SC', name: 'Secunderabad Junction' },
  { code: 'HYB', name: 'Hyderabad Deccan' },
  { code: 'NGP', name: 'Nagpur' },
  { code: 'BPL', name: 'Bhopal Junction' },
  { code: 'INDB', name: 'Indore Junction' },
  { code: 'AGC', name: 'Agra Cantt' },
  { code: 'GWL', name: 'Gwalior Junction' },
  { code: 'JAT', name: 'Jammu Tawi' },
  { code: 'ASR', name: 'Amritsar Junction' },
  { code: 'CDG', name: 'Chandigarh' },
  { code: 'UMB', name: 'Ambala Cantt' },
  { code: 'MDU', name: 'Madurai Junction' },
  { code: 'ERS', name: 'Ernakulam Junction' },
  { code: 'TVC', name: 'Thiruvananthapuram Central' },
  { code: 'MAQ', name: 'Mangaluru Central' },
  { code: 'CBE', name: 'Coimbatore Junction' },
  { code: 'TATA', name: 'Tatanagar Junction' },
  { code: 'RNC', name: 'Ranchi' },
  { code: 'RYP', name: 'Rayanapadu' },
  { code: 'RU', name: 'Renigunta Junction' },
  { code: 'GKP', name: 'Gorakhpur Junction' },
  { code: 'JHS', name: 'Jhansi Junction' },
  { code: 'JP', name: 'Jaipur' },
  { code: 'JU', name: 'Jodhpur' },
  { code: 'UJN', name: 'Ujjain Junction' },
  { code: 'BKN', name: 'Bikaner Junction' },
  { code: 'AII', name: 'Ajmer Junction' },
];
